create table tb_breakfast (id int8 generated by default as identity, options varchar(50), date date, options varchar(50), user_id int8, primary key (id));

create table tb_users (id int8 generated by default as identity, name varchar(50), cpf varchar(50), primary key (id));

alter table if exists tb_breakfast add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (user_id) references tb_users;
